import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionWrapper from "./components/SessionWrapper"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Buy me a Headphone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="bg-[#09090f] text-white overflow-x-hidden">
        <SessionWrapper>
         <Navbar/>
         <div className="cont min-h-screen">
        {children}
         </div>
        <Footer/>
        </SessionWrapper>
        </body>
    </html>
  );
}
